---
title: "Career"
---



### Education

*   M.Sc.  Stochastic Engineering
    + University of Applied Sciences, Munich
    + Thesis: Fractal Brownian Motions an application in fix rate models
*   B. Arts. Economist
    + Sergio Arboleda University 
*   B.Arts. Finance and International Trade
    + Sergio Arboleda University
    + Majoring in Risk Management
    
    
### Teaching    

* Stochastic Calculus 
* Derivatives Instruments
* Risk Management
* Econometrics
* Time Series
* Statistics
* Capital Markets
* Computational Finance

### Conferences

*   2020 Speaker V Congreso Internacional de Investigación en Competitividad y Desarrollo Sostenible de la Red Radar

*  	2017 Attended the ARPM seminary at New York University

*   2018 Speaker at VI Congreso de Investigación Financiera Monterey México

*   2016  Speaker at VI Congreso de Investigación Financiera Guadalajara México

*   2016 Speaker at Congreso Internacional de Riesgo Financiero Medellín Colombia.

*   2015 Speaker at V Congreso de Investigación Financiera México D.F México 


### Papers

*   Martínez Patiño, M. A., & Ariza Garzón, M. J., & Cadena Lozano, J. B. (2021). Relevancia del patrón de persistencia de Hurst en la gestión de portafolios de renta variable. Revista de Métodos Cuantitativos para la Economía y la Empresa, 32, 66-82.

*   Martínez Patiño, M. A., & Ariza Garzón, M. J. (2016). Pronóstico de un título de renta fija en Colombia. Revista mexicana de economía y finanzas, 11(3), 141-159.




